version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hhkk0407
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  shop-webapi:
    image: shopwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5284:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Shop: "Server=postgres;Port=5432;Database=Shop;User Id=postgres;Password=Hhkk0407"
      Logging__LogLevel__Default: "Debug"
      
volumes:
  postgres-data:
    driver: local